<?php

/**
 * Implements hook_preprocess_HOOK()
 */
function ldbase_new_account_preprocess_html(&$variables) {
  $variables['#attached']['library'][] =  'ldbase_new_account/ldbase_new_account';
}

/**
 * Implements hook_link_alter()
 */
function ldbase_new_account_link_alter(&$variables) {
  if ($variables['text'] == 'My account') {
    $variables['text'] = t('My Dashboard');
  }
}
